alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
features:
- buildpack-stack=ubuntu-22
ingress:
  rules:
  - component:
      name: django-neon-quickstart
    match:
      path:
        prefix: /
name: seal-app-dev
region: nyc
services:
- build_command: |-
    pip install -r requirements.txt
    python manage.py makemigrations
    python manage.py migrate
  environment_slug: python
  envs:
  - key: PGHOST
    scope: RUN_AND_BUILD_TIME
    value: new_host
  - key: PGDATABASE
    scope: RUN_AND_BUILD_TIME
    value: neondb
  - key: PGUSER
    scope: RUN_AND_BUILD_TIME
    value: neondb_owner
  - key: PGPASSWORD
    scope: RUN_AND_BUILD_TIME
    value: new_password
  github:
    branch: dev
    deploy_on_push: true
    repo: dougsillars/django-neon-quickstart
  http_port: 8000
  instance_count: 1
  instance_size_slug: apps-s-1vcpu-1gb-fixed
  name: django-neon-quickstart
  run_command: gunicorn django_neon.wsgi:application --bind 0.0.0.0:8000
  source_dir: /