name: Create Neon Branch with GitHub Actions Demo
run-name: Create a Neon Branch 🚀
on:
  pull_request:
    types: [opened]
    branches:
      - main  # Assuming you want to run this action when a PR is opened against the 'dev' branch
jobs:
  Create-Neon-Branch:
    uses: neondatabase/create-branch-action@v5
    with:
      project_id: ep-summer-hall-a4z2l10m
      # optional (defaults to your primary branch)
      #parent: main
      # optional (defaults to neondb)
      #database: my-database
      branch_name: development
      username: neondb_owner
      api_key: ${{ secrets.NEON_API_KEY }}
    id: create-branch
  - run: echo db_url ${{ steps.create-branch.outputs.db_url }}
  - run: echo host ${{ steps.create-branch.outputs.host }}
  - run: echo branch_id ${{ steps.create-branch.outputs.branch_id }}
