name: Create Neon Branch and deploy dev to DO
run-name: Create a Neon Branch 🚀
on:
  pull_request:
    types: [opened]
    branches:
      - main
jobs:
  Create-Neon-Branch:
    runs-on: ubuntu-latest
    steps:
      - name: Verify NEON API Key presence
        run: |
          if [ -z "${{ secrets.NEON_API_KEY }}" ]; then
            echo "NEON_API_KEY is empty"
          else
            echo "NEON_API_KEY is set"
          fi
      - name: Create Neon Branch
        id: create-branch
        uses: neondatabase/create-branch-action@v5
        with:
          project_id: "orange-violet-68318343"
          # optional (defaults to your primary  branch)
          parent: "main" 
          # optional (defaults to neondb)
          database: "neondb"
          branch_name: "development"
          username: "neondb_owner"
          api_key: "${{ secrets.NEON_API_KEY }}"
      - run: echo db_url ${{ steps.create-branch.outputs.db_url }}
      - run: echo host ${{ steps.create-branch.outputs.host }}
      - run: echo branch_id ${{ steps.create-branch.outputs.branch_id }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_KEY }}
      - name: Set environment variables
        run: |
          doctl auth init -t ${{ secrets.DO_KEY }}
          # Update the app with the new specifications from neon
          doctl apps update "4086802c-a10e-4e18-98a1-327f40cef37a" --spec urchin-app.yaml
          doctl apps create-deployment "4086802c-a10e-4e18-98a1-327f40cef37a"
          DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DO_KEY }}

